name: Publish docs to Github pages

on:
  push:
    branches: [master]
  
jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
      
      - name: Build docs directory
        run: npm run docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
          with:
            branch: gh-pages
            folder: docs